version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=partners_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - partners_hub_network

  backend:
    build:
      context: ./partners-hub-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./partners-hub-backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/partners_hub
    depends_on:
      - db
    networks:
      - partners_hub_network

  frontend:
    build:
      context: ./partners-hub-front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./partners-hub-front:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - partners_hub_network

volumes:
  postgres_data:

networks:
  partners_hub_network:
    driver: bridge

